// Type exports for the shared package
export type {
  PlanType,
  PocketKind,
  PocketCategory,
  IncomePattern,
  SpendingHabit,
  PlanName,
  TransactionType,
  ReallocationStatus,
  ReallocationReason,
  MerchantCategory,
  PlanStatus,
  OnboardingInput,
  PlanAssignReason,
  OnboardingAssignResult,
  OnboardingCommitResult,
  User,
  Pocket,
  Plan,
  IncomeEvent,
  FixedExpense,
  Transaction,
  Reallocation,
  MerchantClassification,
  BehaviorEvent,
  DisciplineScore,
} from '../schemas';