#!/usr/bin/env bash
# ============================================================================
# Regenerates apps/api/supabase/migrations/ from the canonical migration
# source at apps/api/src/database/migrations/.
#
# Why this exists: the repo used to have two hand-maintained copies of the
# schema (one under src/database/migrations, one under supabase/migrations)
# and they silently drifted apart — see BACKEND_FRONTEND_AUDIT.md §C1. The
# fix is to have exactly one place a human edits SQL (src/database/migrations)
# and treat supabase/migrations as a build artifact, regenerated by this
# script, that the Supabase CLI reads from.
#
# Usage:
#   npm run db:sync          # from apps/api/
#   ./scripts/sync-supabase-migrations.sh
# ============================================================================
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
API_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

SOURCE_DIR="$API_DIR/src/database/migrations"
TARGET_DIR="$API_DIR/supabase/migrations"

mkdir -p "$TARGET_DIR"

# Only copy the versioned .sql migration files themselves — the .spec.sql /
# .test.sql helper scripts and README.md are dev-only and don't belong in a
# Supabase CLI migrations directory (the CLI applies every .sql file it finds
# there, in filename order, on `supabase db push`).
shopt -s nullglob
copied_any=false
for f in "$SOURCE_DIR"/[0-9]*.sql; do
  base="$(basename "$f")"
  case "$base" in
    *.spec.sql|*.test.sql)
      continue
      ;;
  esac
  cp "$f" "$TARGET_DIR/$base"
  copied_any=true
  echo "synced: $base"
done

if [ "$copied_any" = false ]; then
  echo "No migration files found in $SOURCE_DIR" >&2
  exit 1
fi

cat > "$TARGET_DIR/README.md" <<'EOF'
# Generated directory — do not edit

Every file in this directory is copied verbatim from
`apps/api/src/database/migrations/` by `npm run db:sync`
(`apps/api/scripts/sync-supabase-migrations.sh`).

If you need to change the schema, edit the canonical source in
`apps/api/src/database/migrations/` and re-run `npm run db:sync`.
Hand-editing files in this directory will be silently overwritten,
and is exactly the kind of drift that caused
`BACKEND_FRONTEND_AUDIT.md` §C1 in the first place.
EOF

echo "Done. apps/api/supabase/migrations/ now matches apps/api/src/database/migrations/."
